### ISSUE TITLE
Editor does not work in stack

### ISSUE THREAD

**Issue by CybDis** [marcokreeft87/ha-editor-formbuilder#2]
I'm using a project using your editor: https://github.com/CybDis/lovelace-flower-card-mod

When using the lovelace-flower-card in a vertical-/horizontal stack setting, it does not update the config corresponsing the selected card. It always shows first card (`Flammenblume 1`) instead of the selected card (`Tomate`):

![image](https://github.com/marcokreeft87/ha-editor-formbuilder/assets/10251750/5b71a886-2dd6-47d3-8071-c54af994bedb)

When changing a setting (checking a checkbox) it updates the displayed entities:  
![image](https://github.com/marcokreeft87/ha-editor-formbuilder/assets/10251750/d4998e82-cf60-4038-87d9-e9e6f32b15aa)

So I think some update-trigger is missing to relead the config.  
Would you have a look into it?

**Comment by CybDis** [comment]
sure:

‘‘‘
type: vertical-stack
cards:
  - type: tile
    entity: cover.alle_jalousien
    features:
      - type: cover-open-close
  - type: horizontal-stack
    cards:
      - type: custom:flower-card
        entity: plant.plant_flamme1b
        battery_sensor: sensor.flammenblume1b_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
        name: Flammenblume 1
      - type: custom:flower-card
        entity: plant.plant_flamme2
        battery_sensor: sensor.flammenblume2_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
        name: Flammenblume 2
  - type: horizontal-stack
    cards:
      - type: custom:flower-card
        entity: plant.plant_kasten
        name: xxx
        battery_sensor: sensor.ringelblumen_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
      - type: custom:flower-card
        entity: plant.plant_rose
        name: Rose
        battery_sensor: sensor.rose_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
  - type: horizontal-stack
    cards:
      - type: custom:flower-card
        name: Paprikas
        entity: plant.plant_paprika
        battery_sensor: sensor.paprikakasten_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
      - type: custom:flower-card
        entity: plant.plant_snackpaprika
        name: Snackpaprika
        battery_sensor: sensor.snackpaprika_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
  - type: horizontal-stack
    cards:
      - type: custom:flower-card
        entity: plant.plant_hochbeet
        name: Hochbeet
        battery_sensor: sensor.higrow9_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
      - type: custom:flower-card
        name: Tomate
        entity: plant.plant_tomate
        battery_sensor: sensor.higrow10_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
  - type: horizontal-stack
    cards:
      - type: custom:flower-card
        name: Benjamin
        hide_species: true
        entity: plant.plant_benjamin
        battery_sensor: sensor.benjamin_battery
        show_bars:
          - moisture
        display_type: compact
      - type: custom:flower-card
        hide_species: true
        entity: plant.plant_flamme1
        battery_sensor: sensor.flammenblume1_battery
        show_bars:
          - moisture
        display_type: compact
        name: Blumenkasten

‘‘‘

**Comment by CybDis** [comment]
sure:

type: vertical-stack
cards:
  - type: tile
    entity: cover.alle_jalousien
    features:
      - type: cover-open-close
  - type: horizontal-stack
    cards:
      - type: custom:flower-card
        entity: plant.plant_flamme1b
        battery_sensor: sensor.flammenblume1b_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
        name: Flammenblume 1
      - type: custom:flower-card
        entity: plant.plant_flamme2
        battery_sensor: sensor.flammenblume2_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
        name: Flammenblume 2
  - type: horizontal-stack
    cards:
      - type: custom:flower-card
        entity: plant.plant_kasten
        name: xxx
        battery_sensor: sensor.ringelblumen_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
      - type: custom:flower-card
        entity: plant.plant_rose
        name: Rose
        battery_sensor: sensor.rose_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
  - type: horizontal-stack
    cards:
      - type: custom:flower-card
        name: Paprikas
        entity: plant.plant_paprika
        battery_sensor: sensor.paprikakasten_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
      - type: custom:flower-card
        entity: plant.plant_snackpaprika
        name: Snackpaprika
        battery_sensor: sensor.snackpaprika_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
  - type: horizontal-stack
    cards:
      - type: custom:flower-card
        entity: plant.plant_hochbeet
        name: Hochbeet
        battery_sensor: sensor.higrow9_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
      - type: custom:flower-card
        name: Tomate
        entity: plant.plant_tomate
        battery_sensor: sensor.higrow10_battery
        show_bars:
          - moisture
        display_type: compact
        hide_species: true
  - type: horizontal-stack
    cards:
      - type: custom:flower-card
        name: Benjamin
        hide_species: true
        entity: plant.plant_benjamin
        battery_sensor: sensor.benjamin_battery
        show_bars:
          - moisture
        display_type: compact
      - type: custom:flower-card
        hide_species: true
        entity: plant.plant_flamme1
        battery_sensor: sensor.flammenblume1_battery
        show_bars:
          - moisture
        display_type: compact
        name: Blumenkasten

**Comment by marcokreeft87** [comment]
Hmm don't think the problem lies within the editor code tbh.
A lot of custom cards and a few native HA cards won't display correctly in horizontal-stack or vertical-stack in editor.

Have you tried it without the horizontal-stack?

**Comment by marcokreeft87** [comment]
Ok I will take a look at it. But won't be very soon I'm afraid

**Comment by CybDis** [comment]
That's it - I forked and updated from 'lit-element' to 'lit' and everything now works again  
see -> https://github.com/marcokreeft87/ha-editor-formbuilder/compare/master...CybDis:ha-editor-formbuilder:master

**Comment by marcokreeft87** [comment]
Oh the build failed. Let me check that tomorrow morning

**Comment by CybDis** [comment]
ok.

remember to undo my readme.me changes

**Comment by marcokreeft87** [comment]
Apparently I forgot how the auto publish worked haha. But its published now.
